# 3. Simplex Method
This notebook aims to use the simplex method to solve Linear Programming (LP) problems. The notation that will be used to introduce the simplex method is as below:
$$min \ \ \  \textbf{c}^\mathsf{T}\textbf{x}$$
$$ \ \ \ \ \ s.t. \ \ Ax = b$$
$$x \geq 0$$

Where $\textbf{A}$ is an $m x n$ matrix with rank $m$ and all other vectors have appropriate dimension. $\textbf{c}$ is a column vector.

Suppose we have a basis $B$ and $A$ can be decompose as $A = [B \ \ N]$. Accordingly, any $x$ can be written as:
$$x=\begin{bmatrix}
x_B \\
x_N
\end{bmatrix} = 
\begin{bmatrix}
B^{-1}b \\
0
\end{bmatrix}$$

Cost vector $c$ can be written as:
$$c=\begin{bmatrix}
c_B \\
c_N
\end{bmatrix}$$

In summary, $Ax = B$ can be written as
$$Ax = [B \ \ N]
\begin{bmatrix}
x_b \\
x_N
\end{bmatrix}
= b$$

We will be creating an algorithm to search all the basic feasible solution:

## 5.2 Searching All Basic Feasible Solutions ##

In [6]:
# libraries and packages
using LinearAlgebra
using Combinatorics

In [21]:
#initializing variable parameters
c = [-3; -2; -1; -5; 0; 0; 0];
A = [7 3 4 1 1 0 0 ;
     2 1 1 5 0 1 0 ;
     1 4 5 2 0 0 1 ];
b = [7; 3; 8];

In [3]:
m,n = size(A)

@assert rank(A) == m

In [4]:
obj = Inf
opt_x = zeros(n);

In [8]:
collect(combinations(1:n, m));

In [12]:
for b_idx in combinations(1:n,m)
    B = A[:, b_idx]
    c_B = c[b_idx]
    x_B = inv(B) * b
end


[1, 2, 3][1, 2, 4][1, 2, 5][1, 2, 6][1, 2, 7][1, 3, 4][1, 3, 5][1, 3, 6][1, 3, 7][1, 4, 5][1, 4, 6][1, 4, 7][1, 5, 6][1, 5, 7][1, 6, 7][2, 3, 4][2, 3, 5][2, 3, 6][2, 3, 7][2, 4, 5][2, 4, 6][2, 4, 7][2, 5, 6][2, 5, 7][2, 6, 7][3, 4, 5][3, 4, 6][3, 4, 7][3, 5, 6][3, 5, 7][3, 6, 7][4, 5, 6][4, 5, 7][4, 6, 7][5, 6, 7]

In [22]:
A

3×7 Matrix{Int64}:
 7  3  4  1  1  0  0
 2  1  1  5  0  1  0
 1  4  5  2  0  0  1

In [23]:
b_idx = [2,5,7]

3-element Vector{Int64}:
 2
 5
 7

In [24]:
A[:, b_idx] 

3×3 Matrix{Int64}:
 3  1  0
 1  0  0
 4  0  1