# Vector, Matrix and Array

## 3.1 Vector, Matrix and Array

Below, we will be recreating a couple of vector, matrix and arrays using Julia. Expressing vector, matrix and arrays is very similar to MATLAB

In [1]:
a= [1;2;3]
b = [4 5 6]
A= [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [7]:
A

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [8]:
transpose(A)

3×2 transpose(::Matrix{Int64}) with eltype Int64:
 1  4
 2  5
 3  6

In [16]:
B = [1 3 2; 3 2 2; 1 1 1]

3×3 Matrix{Int64}:
 1  3  2
 3  2  2
 1  1  1

In [17]:
inv(B)

3×3 Matrix{Float64}:
  1.11022e-16   1.0  -2.0
  1.0           1.0  -4.0
 -1.0          -2.0   7.0

In [18]:
B*inv(B)

3×3 Matrix{Float64}:
  1.0          0.0  0.0
  0.0          1.0  0.0
 -2.22045e-16  0.0  1.0

In [19]:
inv(B)[2,1]

1.0000000000000004

## 3.2 Tuple

These types of arrays can be useful for handling network data with nodes and links, for example for storing data like (i,j). 

In [23]:
Sample_pairs = [ (1,2); (3,4); (5,6) ]

3-element Vector{Tuple{Int64, Int64}}:
 (1, 2)
 (3, 4)
 (5, 6)

When you want (i,j,k), simply do:

In [26]:
ijk_array = Array{Tuple{Int64, Int64, Int64}}(undef, 3)

3-element Vector{Tuple{Int64, Int64, Int64}}:
 (0, 1, 2956482560)
 (2, 1, 167378945)
 (4, 1, 1)

In [27]:
ijk_array[1] = (1, 4, 2)

(1, 4, 2)

In [28]:
ijk_array

3-element Vector{Tuple{Int64, Int64, Int64}}:
 (1, 4, 2)
 (2, 1, 167378945)
 (4, 1, 1)

## 3.5 Collection, Dictionary and For-Loop

### For-Loop

In [34]:
for i in 1:5
    if i == 3
        continue
    else
        println("This is a number $i")
    end
end

This is a number 1
This is a number 2
This is a number 4
This is a number 5


### Dictionary

In [37]:
d = Dict()

my_keys = ["Zinedine Zidane", "Magic Johnson", "Yuna Kim"]
my_values = ["football", "basketball", "figure skating"]

for i in 1:length(my_keys)
    d[my_keys[i]] = my_values[i]
end

In [38]:
d

Dict{Any, Any} with 3 entries:
  "Magic Johnson"   => "basketball"
  "Zinedine Zidane" => "football"
  "Yuna Kim"        => "figure skating"

## 3.6 Function

In [41]:
f(x,y) = 3x+y

f (generic function with 1 method)

In [42]:
f(1,3)

6

In [44]:
function my_func(n,m)
    a = zeros(n,1)
    b = ones(m,1)
    return(a,b)
end

my_func (generic function with 1 method)

In [45]:
X,Y = my_func(3,2)

([0.0; 0.0; 0.0;;], [1.0; 1.0;;])

In [46]:
X

3×1 Matrix{Float64}:
 0.0
 0.0
 0.0

In [47]:
Y

2×1 Matrix{Float64}:
 1.0
 1.0

One can use the dot function to carry out a certain function to individual elements

In [49]:
test = sqrt.([9 16])

1×2 Matrix{Float64}:
 3.0  4.0

In [50]:
my_func(x) = sin(x) + 3*x

my_func(3)

9.141120008059866

In [52]:
my_func.([1,2,3,4,5,6,7,8,9,10])

10-element Vector{Float64}:
  3.8414709848078967
  6.909297426825682
  9.141120008059866
 11.243197504692072
 14.041075725336862
 17.720584501801074
 21.656986598718788
 24.989358246623382
 27.412118485241756
 29.45597888911063

In [54]:
rand() * 100

60.071941305215205

In [56]:
sigma = 3
mu = 50
randn(10) .* sigma .+ mu

10-element Vector{Float64}:
 56.44673499345795
 47.822587988444255
 47.787598307033434
 53.44275957119237
 49.4820176494003
 50.330975841968076
 48.57476426390516
 49.259276982111295
 48.82572649657627
 48.10066087624922

In [57]:
function my_randn(n, mu, sigma)
    return randn(n) .* sigma .+ mu
end

my_randn (generic function with 1 method)

In [58]:
my_randn(10,50,3)

10-element Vector{Float64}:
 48.804203813739385
 46.53428890114069
 49.208690357253296
 48.73007544966797
 49.4201621312174
 50.24815293259556
 49.76301275759606
 51.29969040318603
 48.37512521201814
 55.895773327245635

In [60]:
using StatsFuns

normpdf(mu,sigma,52)

0.10648266850745075

In [63]:
norminvcdf(mu,sigma,0.5)

50.0

## 3.7 Plotting

In [64]:
ENV["Python"] = ""

""

In [65]:
using Pkg

Pkg.add("PyPlot")

    Updating registry at `C:\Users\siva1\.julia\registries\General`


    Updating git-repo `https://github.com/JuliaRegistries/General.git`


   Resolving package versions...

   Installed PyPlot ───────── v2.11.0


   Installed Conda ────────── v1.7.0
   Installed VersionParsing ─ v1.3.0
   Installed PyCall ───────── v1.94.1


    Updating `C:\Users\siva1\.julia\environments\v1.8\Project.toml`
  [d330b81b] + PyPlot v2.11.0
    Updating `C:\Users\siva1\.julia\environments\v1.8\Manifest.toml`


  [8f4d0f93] + Conda v1.7.0
  [438e738f] + PyCall v1.94.1
  [d330b81b] + PyPlot v2.11.0
  [81def892] + VersionParsing v1.3.0
    Building Conda ─→ `C:\Users\siva1\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\6e47d11ea2776bc5627421d59cdcc1296c058071\build.log`


    Building PyCall → `C:\Users\siva1\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\53b8b07b721b77144a0fbbbc2675222ebf40a02d\build.log`


Precompiling

 project...

  ✓ PyCall


  ✓ PyPlot
  2 dependencies successfully precompiled in 6 seconds. 221 already precompiled.


In [67]:
using PyPlot

# Preparing a figure object
fig = figure()

# Data
x = range(0, stop=2*pi, length=1000)
y = sin.(3*x)

# Plotting with linewidth and linestyle specified
plot(x, y, color="blue", linewidth=2.0, linestyle="--")

# Labeling the axes
xlabel(L"value of $x$")
ylabel(L"\sin(3x)")

# Title
title("Test plotting")

# Save the figure as PNG and PDF
savefig("plot1.png")
savefig("plot1.pdf")

# Close the figure object
close(fig)

In [68]:
# Data
lower_bound = [4.0, 4.2, 4.4, 4.8, 4.9, 4.95, 4.99, 5.00]
upper_bound = [5.4, 5.3, 5.3, 5.2, 5.2, 5.15, 5.10, 5.05]
iter = 1:8

# Creating a new figure object
fig = figure()

# Plotting two datasets
plot(iter, lower_bound, color="red", linewidth=2.0, linestyle="-",
 marker="o", label=L"Lower Bound $Z^k_L$")
plot(iter, upper_bound, color="blue", linewidth=2.0, linestyle="-.",
 marker="D", label=L"Upper Bound $Z^k_U$")

# Labeling axes
xlabel(L"iteration clock $k$", fontsize="xx-large")
ylabel("objective function value", fontsize="xx-large")

# Putting the legend and determining the location
legend(loc="upper right", fontsize="x-large")

# Add grid lines
grid(color="#DDDDDD", linestyle="-", linewidth=1.0)
tick_params(axis="both", which="major", labelsize="x-large")

# Title
title("Lower and Upper Bounds")

# Save the figure as PNG and PDF
savefig("plot2.png")
savefig("plot2.pdf")

# Closing the figure object
close(fig)

In [69]:
# Data
data = randn(100) # Some Random Data
nbins = 10        # Number of bins

# Creating a new figure object
fig = figure()

# Histogram
plt[:hist](data, nbins)

# Title
title("Histogram")

# Save the figure as PNG and PDF
savefig("plot3.png")
savefig("plot3.pdf")

# Closing the figure object
close(fig)